name: Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install torch
        run: pip install torch --index-url https://download.pytorch.org/whl/cpu
      - name: Install
        run: pip install .[docs]
      - name: Build docs
        run: sphinx-build -b html docs docs/_build/html -W
      - uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: docs-html
          path: docs/_build/html
