name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install torch
        run: pip install torch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 --index-url https://download.pytorch.org/whl/cpu
      - name: Install torch-scatter torch-cluster
        run: pip install torch-scatter torch-cluster -f https://data.pyg.org/whl/torch-2.3.0+cpu.html
      - name: Install
        run: pip install .[test]
      - name: Run tests
        run: pytest -n auto --cov -m "not serial" && pytest -m serial
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-${{ matrix.python-version }}
          path: .coverage
